---
name: Module-Starter-CSJEWELL
version: 0.100
author:
  - 'Curtis Jewell <CSJewell@cpan.org>'
abstract: Create a module like CSJEWELL does it.
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Module-Starter-CSJEWELL
  homepage: http://csjewell.comyr.com/perl/
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Module-Starter-CSJEWELL/
build_requires:
  Test::More: 0.61
requires:
  Module::Starter: 1.52
  Pod::Readme: 0.09
  Software::License: 0.012
  parent: 0.221
  perl: 5.008001
configure_requires:
  Module::Build: 0.33
provides:
  Module::Starter::CSJEWELL:
    file: lib/Module/Starter/CSJEWELL.pm
    version: 0.100
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
