---
abstract: 'Create a module like CSJEWELL does it.'
author:
  - 'Curtis Jewell <CSJewell@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.33
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Starter-CSJEWELL
provides:
  Module::Starter::CSJEWELL:
    file: lib/Module/Starter/CSJEWELL.pm
    version: 0.200
requires:
  Module::Starter: 1.52
  Pod::Readme: 0.09
  Software::License: 0.012
  parent: 0.221
  perl: 5.008001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Module-Starter-CSJEWELL
  homepage: http://csjewell.comyr.com/perl/
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/csjewell/module-starter-csjewell/
version: 0.200
